image: node:latest

stages:
  - build
  - test
  - deploy-staging
  - deploy-prod

cache:
  paths:
    - node_modules/
    - yarn.lock

build:
  stage: build
  script:
    - yarn
    - yarn build

test:
  stage: test
  script:
    - yarn
    - yarn test

deploy-staging:
  stage: deploy-staging
  only: [master]
  script:
    - yarn install --prod
    - apt-get update -yq
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=enframe-test-app-staging --api-key=$HEROKU_API_KEY

deploy-prod:
  stage: deploy-prod
  when: manual
  only: [master]
  allow_failure: false
  script:
    - yarn install --prod
    - apt-get update -yq
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=enframe-test-app-prod --api-key=$HEROKU_API_KEY
